export { default as userRouter } from './user/user.router'
export { default as authRouter } from './auth/auth.router'
export {default as bigAdminRouter} from '../modules/role-menegment/big_admin/bigAdmin.router'
export { default as studentRouter } from '../modules/role-menegment/students/student.router'
export { default as mentorRouter } from '../modules/role-menegment/mentor/mentor.router'
export { default as educationRouter } from './education/education.router'
export { default as adminRouter } from '../modules/role-menegment/admin/admin.router'
export {default as callCenterRouter} from './role-menegment/callcenter/callcenter.router'
export {default as managerRouter} from './role-menegment/manager/manager.router'
